version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
    volumes:
      - ./ignored/pgdata:/var/lib/postgresql/data
      # - ./db/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    restart: always
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 50

  metabase:
    # image: metabase/metabase # As of 2024-01-12 this doesn't work on an M2 chip
    image: quackmeup-metabase # First run ./scripts/metabase/build_docker.sh
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: host.docker.internal
      MB_PLUGINS_DIR: /home/plugins
    volumes:
      - ./ignored:/container/directory
    expose:
      - 3000
    ports:
      - 3000:3000
