version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
    volumes:
      - ./ignored/pgdata:/var/lib/postgresql/data
      # - ./db/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    restart: always
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 50

  metabase:
    # image: metabase/metabase # As of 2024-01-12 this doesn't work on an M2 chip
    image: quackmeup-metabase # First run ./scripts/metabase/build_docker.sh
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: host.docker.internal
      MB_PLUGINS_DIR: /home/plugins
      # MB_IS_METABOT_ENABLED: true
    volumes:
      - ./ignored:/container/directory
    expose:
      - 3000
    ports:
      - 3000:3000

  hive-metastore-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hive
      POSTGRES_USER: hive
      POSTGRES_DB: metastore
    volumes:
      - ./ignored/hive/metastore-db:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    # image: bde2020/hive-metastore-postgresql
    environment:
      HIVE_DB_HOST: hive-metastore-db
      HIVE_DB_USERNAME: hive
      HIVE_DB_PASSWORD: hive
      HIVE_DB_DATABASE: metastore
    depends_on:
      - hive-metastore-db
    ports:
      - '9083:9083'
    volumes:
      - ./ignored/tmp_parquet:/hive/data
      - ./scripts/hive/conf:/opt/hive/conf

  minio:
    hostname: minio
    image: minio/minio
    ports:
      - '9000:9000'
    volumes:
      - ./ignored/minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data

  presto-coordinator:
    image: prestodb/presto:latest
    ports:
      - "8080:8080"
    command:
      - --server
      - etc/presto
    volumes:
      - ./scripts/presto/etc:/opt/presto-server/etc
      # - ./ignored/formatted_logs:/usr/local/presto/data
      # - ./ignored/formatted_logs_parquet:/usr/local/presto/data
      # - ./ignored/tmp:/usr/local/presto/data
      - ./ignored/tmp_parquet:/usr/local/presto/data
    environment:
      - NODE_ENVIRONMENT=production
      - IS_COORDINATOR=true
    depends_on:
      - hive-metastore
